✨ Introduce TestSuite
jovotech/jovo-framework pull request #1033
Opened 2021-09-20 14:15 UTC by rubenaeg

## Proposed changes
This PR introduces a major overhaul for the TestSuite.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

2021-09-21 07:45 UTC, aswetlow requested changes
Great PR! Can't wait to use the TestSuite.

* Please update some parts (DbPlugin, user get id()) after https://github.com/jovotech/jovo-framework/pull/1031 is merged to master
* Remove Github linter warnings

2021-09-21 07:45 UTC, aswetlow commented on framework/src/testsuite/TestDb.ts
> +  async loadData(jovo: Jovo): Promise<void> {
Needs to be updated after changes in the DbPlugin: https://github.com/jovotech/jovo-framework/pull/1031

2021-09-21 07:45 UTC, aswetlow commented on framework/src/testsuite/TestUser.ts
> +    return this.jovo?.$request?.userId || 'TestUser';
Should return `undefined` instead of `TestUser` after the changes in https://github.com/jovotech/jovo-framework/pull/1031

2021-09-22 08:26 UTC, jankoenig approved these changes
Just updated the docs. Please take a look to see if I missed anything. Thanks! Good to go from my side ✅

2021-09-22 14:11 UTC, merged