:sparkles: Implement isJovoCliError
jovotech/jovo-framework pull request #1141
Opened 2021-11-26 16:41 UTC by rubenaeg

## Proposed changes
This PR adds an instance check for `JovoCliError` according to [this PR](https://github.com/jovotech/jovo-cli/pull/268).

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

2021-11-29 10:56 UTC, aswetlow approved these changes

2021-11-29 14:25 UTC, jankoenig requested changes

2021-11-29 14:25 UTC, jankoenig commented on platforms/platform-alexa/src/cli/utilities.ts
> +          'Read more here: https://developer.amazon.com/docs/smapi/quick-start-alexa-skills-kit-command-line-interface.html',
´learnMore` should only be a link

2021-11-30 11:53 UTC, rubenaeg commented on platforms/platform-alexa/src/cli/utilities.ts
> +          'Read more here: https://developer.amazon.com/docs/smapi/quick-start-alexa-skills-kit-command-line-interface.html',
Fixed :+1:

2021-12-02 14:54 UTC, jankoenig approved these changes

2021-12-09 13:36 UTC, merged