♻️ Refactor `JovoLogger`
jovotech/jovo-framework pull request #1190
Opened 2022-01-19 18:05 UTC by m-ripper

## Proposed changes
- Refactor `JovoLogger` to use [loglevel](https://github.com/pimterry/loglevel) instead of [tslog](https://tslog.js.org/#/) due to issues with browser-compatibility when using tslog.
- Allow a string to be passed as constructor parameter `JovoError` to pass a message only
- The properties and order of properties of `JovoError` that should be listed when printing a `JovoError` with the `JovoLogger`  can be modified by passing `properties` to the config of `JovoLogger`. 
- Remove tslogMockPlugin from web-client build-script

> Before merging we will have to discuss how the current `properties`-property in `JovoLoggerConfig` is supposed to be named.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

2022-01-24 13:13 UTC, jankoenig commented on common/src/JovoLogger.ts
> +  disableStyling: boolean;
I'm not 100% sure on the naming of that property.  `logging` includes a property called `styling`. `logger` uses `disableStyling`. I think we should be consistent here

2022-01-24 13:13 UTC, jankoenig commented on common/src/JovoLogger.ts
> +  properties: Array<keyof JovoError>;
Have we finalized that property name yet?

2022-01-26 09:14 UTC, jankoenig requested changes
I've just updated the docs a bit.

Could you change `properties` to `errorProperties`? After that, I think this is ready to merge 👍🏻  Thanks!

2022-01-26 11:14 UTC, aswetlow approved these changes

2022-01-26 11:33 UTC, jankoenig approved these changes

2022-01-26 11:33 UTC, merged