implement `$device.getTimezone()` on Alexa
jovotech/jovo-framework pull request #1213
Opened 2022-02-02 06:14 UTC by jtfell

## Proposed changes

Adds a convenience method for accessing the system timezone on Alexa. See docs included in the change.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

2022-02-02 08:43 UTC, jankoenig commented
Thank you! Looks good, thanks also for adding documentation 🎉

2022-02-02 08:43 UTC, jankoenig approved these changes

2022-02-02 08:46 UTC, aswetlow approved these changes

2022-02-03 11:06 UTC, jankoenig requested changes
One thing that came up in a conversation with @aswetlow: Could we rename `timezone` to `timeZone`?

2022-02-10 12:41 UTC, jankoenig approved these changes

2022-02-10 12:45 UTC, merged