:sparkles: Add Google BigQuery Analytics plugin
jovotech/jovo-framework pull request #1478
Opened 2022-12-10 22:31 UTC by rmtuckerphx

## Proposed Changes

Track analytics using Google BigQuery.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

2023-01-02 10:02 UTC, aswetlow requested changes
🚀 Thank you for the PR @rmtuckerphx 
I added a few comments and requested changes.

2023-01-02 10:02 UTC, aswetlow commented on integrations/analytics-bigquery/docs/README.md
> +await this.$bigquery.addEvent({
I think we should change `$bigquery` to `$bigQuery` since the official name is Google BigQuery.

2023-01-02 10:02 UTC, aswetlow commented on integrations/analytics-bigquery/src/BigQueryAnalytics.ts
> +  // async eventT(jovo: Jovo, payload: AnyObject | undefined): Promise<void> {
Please remove unused code, thank you.

2023-01-02 10:02 UTC, aswetlow commented on integrations/analytics-bigquery/src/JovoBigQuery.ts
> +    this.requestId = uuidv4();
This makes me think of abstracting `requestId` and adding it to the  `$jovo` instance. There are many use cases. 

We also use a `requestId` in our Jovo Inbox plugin.

2023-01-02 10:02 UTC, aswetlow commented on integrations/analytics-bigquery/src/JovoBigQuery.ts
> +    this.requestId = uuidv4();
Using the Jovo Inbox and the BigQuery plugin at the same time would mean there's the same `requestId` for the same request. Debugging is a lot easier with consistent data. 

Does it make it sense?

2023-01-02 10:02 UTC, aswetlow commented on integrations/analytics-bigquery/src/JovoBigQuery.ts
> +      console.log('BigQuery addEvent', { event });
Could you add this above every line you use `console` ?
`// eslint-disable-next-line no-console`

2023-01-02 10:02 UTC, aswetlow commented on integrations/analytics-bigquery/src/JovoBigQuery.ts
> +  async addError(error: Error) {
The linter requests a return type :)

2023-01-02 10:02 UTC, aswetlow commented on integrations/analytics-bigquery/src/JovoBigQuery.ts
> +        sessionStart: Date.now(),
I think this is not necessary. You can use `jovo.$session.createdAt`

2023-01-02 18:02 UTC, rmtuckerphx commented on integrations/analytics-bigquery/src/JovoBigQuery.ts
> +    this.requestId = uuidv4();
@aswetlow  That makes sense, are you going to refactor `requestId`?

2023-01-02 18:04 UTC, rmtuckerphx commented on integrations/analytics-bigquery/src/BigQueryAnalytics.ts
> +  // async eventT(jovo: Jovo, payload: AnyObject | undefined): Promise<void> {
@aswetlow  I'll remove. But I left that there so you could consider it in context of my other PR https://github.com/jovotech/jovo-framework/pull/1406

2023-01-04 21:54 UTC, rmtuckerphx commented
@aswetlow I think this is ready to go

2023-01-05 16:22 UTC, jankoenig commented
Hi @rmtuckerphx,

Thank you for the PR! Great work.

I just updated the docs and everything is good to go except one thing I'd like to talk to you about. The service account key file and `libraryConfig`.

Instead of providing the `projectId` and the `fileName` (or path, which I think is a bit unintuitive as we already import the file) as part of the `libraryConfig`, would it make sense to pass the whole `serviceAccount` file? We do the same thing in Google`s Business Messages platform integration: https://www.jovo.tech/marketplace/platform-googlebusiness#configuration

Do you think this would work? We could still use `libraryConfig` for additional, optional client configurations.

Thanks,
Jan

2023-01-05 17:10 UTC, rmtuckerphx commented
@jankoenig I'm open to the changes for `libraryConfig` if they work. Not that familiar with Google.

2023-02-08 10:31 UTC, sadlowskij commented
Hey @jankoenig and @rmtuckerphx! I took a look into this, experimented a bit and found this looked at the documentation of the  [BigQueryOptions](https://googleapis.dev/nodejs/bigquery/latest/global.html#BigQueryOptions), which shows that there are multiple ways of authenticating, including using the serviceaccount json.

Here are my propositions to go further with this

1. Remove throwing erros when `keyFilename` or `projectId` are not provided in the `libraryOptions` as these are not required (see docs). This way it is up to the user how they want to authenticate themselves, e. g. by using the `GCLOUD_PROJECT` enivornment variable.
2. Add example in the docs how the serviceAccount is used like it is in used in Google Business Messages. In this case the serviceAccount is used like this
```
new BigQueryAnalytics({
  appId: 'jovo',
  datasetId: 'jovo',
  tableId: 'jovo',
  libraryOptions: {
    credentials: serviceAccount,
  },
}),
```
The one thing that is confusing to me is that the credentials interface in the BigQueryOptions does not include `projectId` and the other fields but only `client_email` and `private_key`, but just providing the whole imported serviceAccount JSON with with `projectId` and all works just fine in my tests.

Doing it this way makes it very flexible for the user, when it comes to authentication. The only thing that's still unclear is why `credentials` in the `BigQueryOptions` has this restricted interface.

If this approach is okay with you, I can make a PR to Marks Fork.

2023-02-08 10:45 UTC, jankoenig commented
Thank you @sadlowskij, this sounds great!

2023-02-08 12:06 UTC, sadlowskij commented
Okay this is the [PR](https://github.com/rmtuckerphx/jovo-framework/pull/1)

2023-02-10 06:24 UTC, rmtuckerphx commented
@aswetlow I've lost track of what is blocking this now. Please advise.

2023-02-21 12:27 UTC, jankoenig approved these changes

2023-02-21 12:28 UTC, merged