expose tts config - pitch and rate, add resetSessionOnRepromptLimit
jovotech/jovo-framework pull request #1557
Opened 2023-05-18 20:32 UTC by marcher357

## Proposed Changes

Expose rate and pitch from speechsynthesis.ts and add resetsessiononrepromptlimit property to repromptprocessor.ts. 

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

2023-05-18 21:24 UTC, rmtuckerphx commented
@aswetlow @jankoenig I've been working with my co-worker on this PR.
Can you please take a look?

2023-05-23 08:54 UTC, jankoenig approved these changes
Looks great. Thank you @marcher357 and @rmtuckerphx 🎉

2023-05-23 09:05 UTC, aswetlow requested changes

2023-05-23 09:05 UTC, aswetlow commented on clients/client-web/src/standalone/SpeechSynthesizer.ts
> +      if (this.config.pitch) {
According to the docs (https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/pitch#value)
pitch = 0 is a valid value. 

`this.config.pitch` = 0 wouldn't be set. I would recommend checking for not undefined

2023-05-23 09:06 UTC, aswetlow commented
Thank you for the PR @marcher357 and @rmtuckerphx

2023-05-23 17:46 UTC, marcher357 commented on clients/client-web/src/standalone/SpeechSynthesizer.ts
> +      if (this.config.pitch) {
done

2023-05-23 18:08 UTC, aswetlow commented on clients/client-web/src/standalone/SpeechSynthesizer.ts
> +      if (this.config.pitch) {
thank you

2023-05-23 18:08 UTC, aswetlow approved these changes

2023-05-31 08:33 UTC, merged