🏷️ ♻️ Refactor typings `Jovo`-typings
jovotech/jovo-framework pull request #975
Opened 2021-07-23 14:35 UTC by m-ripper

## Proposed changes
The correct types are now returned for platform-specific Jovo-instances.

Example:
`this.$alexa.$device` will return an `AlexaDevice`-instance and also have the correct type.
Before, type-hinting assumed a `JovoDevice` was returned.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

2021-07-23 15:01 UTC, rubenaeg approved these changes

2021-07-23 15:06 UTC, rubenaeg requested changes
Could you fix/ignore the failing tests so the workflow is running successfully again?

2021-08-02 16:40 UTC, jankoenig approved these changes

2021-08-02 16:44 UTC, aswetlow approved these changes

2021-08-02 18:22 UTC, rubenaeg approved these changes

2021-08-03 09:49 UTC, merged